# Generated by Django 3.2.16 on 2023-01-20 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='board_relation',
        ),
    ]
